apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: studyhub-dev
spec:
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    
    - name: external
      port: 9094
      targetPort: 9094
      
  selector:
    app: kafka