apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: studyhub-dev
spec:
  serviceName: "kafka" 
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.8.0
        ports:
        - containerPort: 9092  # INTERNAL k8s
        - containerPort: 9093  # Controller
        - containerPort: 9094  # EXTERNAL port-forward
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller" 
        
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        
        - name: KAFKA_LISTENERS
          value: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
        
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka.studyhub-dev.svc.cluster.local:9092,EXTERNAL://localhost:9094"
        
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"

        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-0.kafka.studyhub-dev.svc.cluster.local:9093"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: CLUSTER_ID
          value: "5L6g3nShT-eMCtK--X86sw"
