spring:
  application:
    name: chat-service
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/studyhub

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG
    com.studyhub: DEBUG
    org.springframework.security: DEBUG